package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/dnnrly/layli/internal/composition"
	"github.com/dnnrly/layli/layout"
	"github.com/spf13/cobra"
)

func main() {
	err := Execute()
	if err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() error {
	var output string
	var layoutAlgo string
	var showGrid bool

	var rootCmd = &cobra.Command{
		Use:   "layli [flags] [layout file]",
		Short: "Create ASCII diagrams with automatic layout",
		Long:  `Layli generates SVG diagrams from YAML layout descriptions.`,
		Args:  cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
		RunE: func(cmd *cobra.Command, args []string) error {
			if output == "" {
				output = strings.ReplaceAll(args[0], ".layli", "")
				output = fmt.Sprintf("%s.svg", output)
			}

			app := composition.NewGenerateDiagram(showGrid)
			if err := app.Execute(args[0], output); err != nil {
				return mapError(err)
			}
			return nil
		},
	}

	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "", "output file or directory/")
	rootCmd.PersistentFlags().StringVarP(&layoutAlgo, "layout", "l", "flow-square", "the layout algorithm")
	rootCmd.PersistentFlags().BoolVar(&showGrid, "show-grid", false, "show the path grid dots (great for debugging)")

	rootCmd.AddCommand(
		&cobra.Command{
			Use:   "to-absolute [flags] [layout file]",
			Short: "convert a Layli generated SVG into a layli file that can regenerate it",
			Long:  `Parse an SVG generated by layli and convert it to a layli configuration file with absolute positioning.`,
			Args:  cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
			RunE: func(cmd *cobra.Command, args []string) error {
				f, err := os.Open(args[0])
				if err != nil {
					return fmt.Errorf("opening input: %w", err)
				}

				svg, err := io.ReadAll(f)
				if err != nil {
					return fmt.Errorf("reading input: %w", err)
				}

				err = layout.AbsoluteFromSVG(string(svg), func(data string) error {
					return os.WriteFile(output, []byte(data), 0644)
				})
				if err != nil {
					return fmt.Errorf("generating layli file %s: %w", output, err)
				}

				return nil
			},
		})

	return rootCmd.Execute()
}

func mapError(err error) error {
	msg := err.Error()
	switch {
	case strings.HasPrefix(msg, "parse config: reading config file: open "):
		return fmt.Errorf("opening input: %s", strings.TrimPrefix(msg, "parse config: reading config file: "))
	case strings.HasPrefix(msg, "parse config:"):
		return fmt.Errorf("creating config: %s", strings.TrimPrefix(msg, "parse config: "))
	case strings.HasPrefix(msg, "render diagram:"):
		return fmt.Errorf("drawing diagram: %s", strings.TrimPrefix(msg, "render diagram: "))
	default:
		return err
	}
}
