package layli

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestVertexMap_Count(t *testing.T) {
	m := NewVertexMap(20, 20)

	assert.Equal(t, 400, m.CountAvailable(false))
	assert.Equal(t, 0, m.CountAvailable(true))

	m.Set(1, 2, true)
	m.Set(1, 3, true)
	m.Set(1, 4, true)

	assert.Equal(t, 397, m.CountAvailable(false))
	assert.Equal(t, 3, m.CountAvailable(true))
}

func TestVertexMap_String(t *testing.T) {
	m := NewVertexMap(20, 20)

	assert.Equal(t, strings.ReplaceAll(
		`....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................`, "	", ""), m.String(), m)
	assert.Equal(t, 0, m.CountAvailable(true))

	m.Set(1, 2, true)
	m.Set(1, 3, true)
	m.Set(1, 4, true)

	assert.Equal(t, strings.ReplaceAll(
		`....................
		....................
		.x..................
		.x..................
		.x..................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................
		....................`, "	", ""), m.String(), m)
}

func TestVertexMap_MapAvailable(t *testing.T) {
	m := NewVertexMap(20, 20)

	m.MapAvailable(func(x, y int) bool {
		return (x+y)%2 == 0
	})

	assert.Equal(t, 200, m.CountAvailable(true), m)
}
