// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Graph is an autogenerated mock type for the Graph type
type Graph struct {
	mock.Mock
}

// AddMappedArc provides a mock function with given fields: from, to, distace
func (_m *Graph) AddMappedArc(from string, to string, distace int64) error {
	ret := _m.Called(from, to, distace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(from, to, distace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGraph creates a new instance of Graph. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGraph(t interface {
	mock.TestingT
	Cleanup(func())
}) *Graph {
	mock := &Graph{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
