// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LayoutDrawer is an autogenerated mock type for the LayoutDrawer type
type LayoutDrawer struct {
	mock.Mock
}

// Circle provides a mock function with given fields: x, y, r, s
func (_m *LayoutDrawer) Circle(x int, y int, r int, s ...string) {
	_va := make([]interface{}, len(s))
	for _i := range s {
		_va[_i] = s[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, x, y, r)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Roundrect provides a mock function with given fields: x, y, w, h, rx, ry, s
func (_m *LayoutDrawer) Roundrect(x int, y int, w int, h int, rx int, ry int, s ...string) {
	_va := make([]interface{}, len(s))
	for _i := range s {
		_va[_i] = s[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, x, y, w, h, rx, ry)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// TextEnd provides a mock function with given fields:
func (_m *LayoutDrawer) TextEnd() {
	_m.Called()
}

// Textspan provides a mock function with given fields: x, y, t, s
func (_m *LayoutDrawer) Textspan(x int, y int, t string, s ...string) {
	_va := make([]interface{}, len(s))
	for _i := range s {
		_va[_i] = s[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, x, y, t)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// NewLayoutDrawer creates a new instance of LayoutDrawer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayoutDrawer(t interface {
	mock.TestingT
	Cleanup(func())
}) *LayoutDrawer {
	mock := &LayoutDrawer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
