name: Release workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - uses: actions/setup-go@v1
        env:
          GO111MODULE: on
        with:
          go-version: '1.16'
      - name: Test
        run: make ci-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Deps
      run: make build-deps
      env:
        GO111MODULE: on
    - name: Perform release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO111MODULE: on
      if: success()
